--- @meta
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- Encapsulates a background task for asynchronous execution, including
--- the callback function to be invoked and its associated arguments.
---
--- @class dispatch.backgroundTask
--- 
--- @field callback  function
--- @field arguments unknown[]
---
