--- @meta
--
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- A function that schedules the asynchronous execution of a callback function,
--- allowing for optional arguments and ensuring non-blocking operation.
--- 
--- @alias dispatch.executeCallbackAsync fun(callback: function, arguments?: unknown[])
---
