---@meta

---
--- Represents a context manager that holds objects identified by unique strings. 
--- This class allows retrieving and exposing objects within the context, ensuring 
--- that object identifiers remain unique and accessible through the `use` method.
---
--- @class context
--- @field objects? table<string, unknown> "Holds registered objects, identified by their unique string keys."
--- 
--- @field use      fun(self: context, identifier: string): unknown "Retrieves an object by its identifier. Throws an error if the identifier is not registered."
--- @field expose   fun(self: context, identifier: string, object: unknown) "Registers an object with a unique identifier. Throws an error if the identifier is already in use."
---
