--- @meta
--
--      #
--     # #   #    #  ####  #    # ###### #    # #####
--    #   #  #    # #    # ##  ## #      ##   #   #
--   #     # #    # #      # ## # #####  # #  #   #
--   ####### #    # #  ### #    # #      #  # #   #
--   #     # #    # #    # #    # #      #   ##   #
--   #     #  ####   ####  #    # ###### #    #   #
--
-- World of Warcraft addon ecosystem, created by Erik Riklund (2024)
--

--
--- Acts as a blueprint for defining the structure and data types of complex objects,
--- similar to a template for creating structured documents.
--
--- @class schema : {[string]: property|schema}
--

--
--- Acts as a building block for defining a single attribute within a larger
--- schema, specifying the attribute's expected data type, whether it is optional,
--- and a default value if applicable.
--
--- @class property
--
--- @field type string|schema
--- @field optional? boolean
--- @field default? any
--

--
--- Represents a named element that can be passed into a function, specifying its expected
--- data type and other validation rules, similar to a variable with additional constraints.
--
--- @class parameter : property
--- @field name string
--

--
--- Encapsulates the outcome of a validation process, storing the potentially modified value
--- and an optional error message if the validation failed.
--
--- @class validation_result
--
--- @field value any
--- @field error? string
--

--
--- Represents an ordered collection of elements, where each element is associated
--- with a numerical index.
--
--- @class list<value> : {[integer]: value}
--

--
--- Represents an unordered collection of key-value pairs, where each unique key is
--- associated with a corresponding value.
--
--- @class map<key,value> : {[key]: value}
--
