--- @meta
--
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- API interface designed specifically for plugin interaction with communication
--- channels. It provides methods for plugins to invoke a channel (send a message or data),
--- register listeners to receive messages from a channel, and remove those listeners when
--- they are no longer needed.
--- 
--- @class network.api
--- 
--- @field invokeChannel           fun(self: plugin, name: string, payload?: unknown[])
--- @field registerChannelListener fun(self: plugin, channel: string, listener: listeners.listener)
--- @field removeChannelListener   fun(self: plugin, channel: string, identifier: string)
---
