--- @meta
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- Configuration options for a network channel, including owner,
--- internal access restriction, and asynchronous operation.
--- 
--- @class network.channelOptions
--- 
--- @field owner?    string
--- @field internal? boolean
--- @field async?    boolean
---
