--- @meta
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- Manages communication channels within the framework. It provides methods
--- for reserving new channels, registering and removing listeners on those channels
--- (with optional context association), and invoking channels to broadcast messages or data.
--- 
--- @class network.controller
--- 
--- @field reserveChannel   fun(name: string, options?: network.channelOptions)
--- @field registerListener fun(channel: string, listener: listener, context?: plugin)
--- @field removeListener   fun(channel: string, identifier: string, context?: plugin)
--- @field invokeChannel    fun(name: string, payload?: unknown[], context?: plugin)
---
