@startuml Cogspinner
!include style.puml

component "framework" as Framework <<API>>

note top of Framework
  The framework API is primarily used for plugin
  registration, enabling easy access to its features.
end note

component "plugins" as Plugins <<manager>>

Framework ..|> Plugins

component "plugin" as Plugin <<object>>

note left of Plugin
  The plugin object streamlines development by providing a
  simplified interface for common tasks like event handling
  and saved variable management.
end note

Plugins ==> Plugin : <<create>>

component "network" as Network <<controller>>

Plugin .|> Network

component "events" as Events <<handler>>

Events => Network
Plugin .|> Events

component "tasks" as Tasks <<handler>>

Events ==> Tasks
Network ==> Tasks

component "locales" as Locales <<manager>>

Framework .down.|> Locales
Plugins -[hidden]left-> Locales
Plugin .|> Locales

component "storage" as DataStore <<controller>>

DataStore ==> Network
Plugin .|> DataStore

component "services" as Services <<manager>>

Framework ..|> Services

@enduml