@startuml Cogspinner
!include style.puml

component "framework" as Framework <<API>>

component "plugins" as Plugins <<manager>>

Framework ..> Plugins

component "plugin" as Plugin <<object>>

Plugins ==> Plugin : <<create>>

component "network" as Network <<controller>>

Plugin ..> Network

component "events" as Events <<handler>>

Plugin ..> Events

component "tasks" as Tasks <<handler>>

Framework ..> Tasks

Network -up-> Tasks
Events -up-> Tasks

component "locales" as Locales <<manager>>

Plugin .left.> Locales

component "storage" as DataStore <<controller>>

Plugin .right.> DataStore

component "services" as Services <<manager>>

Framework .left.> Services

component "commands" as Commands <<handler>>

Plugin ..> Commands

component "configuration" as Config <<handler>>

Plugin ..> Config

component "tooltips" as Tooltips <<controller>>

Framework .right.> Tooltips

@enduml