@startuml Cogspinner
!include style.puml

component "framework" as Framework <<API>>

component "plugins" as Plugins <<manager>>

Framework ..> Plugins

component "plugin" as Plugin <<object>>

Plugins ==> Plugin : <<create>>

component "network" as Network <<controller>>

Plugin .left.> Network
Plugins --> Network

component "events" as Events <<handler>>

Plugin ..> Events

component "tasks" as Tasks <<handler>>

Framework ..> Tasks

Network -> Tasks
Events --> Tasks

component "locales" as Locales <<manager>>

Plugin .> Locales

component "storage" as DataStore <<controller>>

Plugin ..> DataStore

component "services" as Services <<manager>>

Framework ..> Services

component "commands" as Commands <<handler>>

Plugin ..> Commands

component "settings" as Config <<handler>>

Plugin ..> Config
Config -> DataStore

component "tooltips" as Tooltips <<controller>>

Framework ..> Tooltips

@enduml