---@meta

---
--- Represents the `exception` class, which provides utility methods for handling different
--- types of errors. The `generic` method is used for general errors, while the `type` method
--- is designed to throw errors for type mismatches in function arguments.
--- 
--- @class exception
--- @field generic fun(message: string, ...: string) "Throws a generic error, optionally formatted with additional arguments."
--- @field type fun(label: string, expected: string|string[], recieved: string) "Throws an error for argument type mismatches, specifying the expected and received types."
---
