--- @meta

---
--- Represents a plugin within the framework. Each plugin is uniquely identified by 
--- its `identifier`, which is used to register and manage it within the system.
---
--- @class plugin : events.api, network.api
--- 
--- @field identifier? string "A unique identifier for the plugin, used for registration and management."
--- @field storage? table "..."
---
