---@meta

---
--- ?
---
---@class BackboneBorders
---
---@field topBorder Texture
---@field bottomBorder Texture
---@field leftBorder Texture
---@field rightBorder Texture
---
---@field topBorderShader? Texture
---@field bottomBorderShader? Texture
---@field leftBorderShader? Texture
---@field rightBorderShader? Texture
---

---
--- ?
---
---@class BackboneBorderColors
---
---@field border? string
---@field borderShader? string
---
