--- @meta
--
--      #
--     # #   #    #  ####  #    # ###### #    # #####
--    #   #  #    # #    # ##  ## #      ##   #   #
--   #     # #    # #      # ## # #####  # #  #   #
--   ####### #    # #  ### #    # #      #  # #   #
--   #     # #    # #    # #    # #      #   ##   #
--   #     #  ####   ####  #    # ###### #    #   #
--
-- World of Warcraft addon framework, created by Erik Riklund (2024)
--

--
--- @class library.type
--
--- @field production_mode boolean
--
--- @field examine fun(value: any): string
--- @field validate fun(value: any, options: type.validation.options, parent?: string): type.validation.result
--- @field validate_schema fun(target: table, schema: type.schema, parent?: string): type.validation.result
--
--- @field required fun(expected_type: string | type.schema): type.validation.options
--- @field optional fun(expected_type: string | type.schema, default_value?: any): type.validation.options
--- @field declare fun(...: type.parameter): ...
--
