@startuml Cogspinner

skinparam ClassFontSize 12pt
skinparam ClassFontName Consolas
skinparam ComponentBackgroundColor GhostWhite
skinparam ComponentBorderColor #565656
skinparam ComponentFontStyle normal
skinparam ComponentFontSize 12pt
skinparam ComponentFontName Consolas
skinparam ComponentStereotypeFontName Consolas
skinparam ComponentStereotypeFontSize 10pt
skinparam ComponentStereotypeFontColor #515151
skinparam InterfaceBackgroundColor Orange
skinparam NoteFontName Franklin Gothic Medium
skinparam NoteFontSize 12pt
skinparam NoteFontColor black
skinparam NoteBackgroundColor #FEFFDD
skinparam NoteBorderColor #96968D
skinparam ArrowFontName Consolas
skinparam ArrowFontSize 10pt

component "framework" as Framework <<API>>
component "plugins" as Plugins <<manager>>

Framework ..> Plugins : <<expose>>

component "plugin" as Plugin <<object>>

Plugins --> Plugin : <<create>>

component "callback" as Callback <<handler>>

Framework ..> Callback : <<expose>>

component "network" as Network <<controller>>

Plugins --> Network : <<use>>
Network --> Callback : <<use>>
Plugin .> Network : <<expose>>

component "event" as Event <<handler>>

Event --> Callback : <<use>>
Plugin ..> Event : <<expose>>

@enduml