--- @meta
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            

--
--- Represents an ordered collection of elements (a list), providing methods for basic manipulation.
---
--- @class List
---
--- @field values unknown[] The underlying array storing the list's elements.
--- @field getElementAt fun(self: List, index: number): unknown Retrieves the element at the specified `index`.
--- @field find fun(self: List, searchValue: unknown): number  Finds the first index of the `searchValue` in the list, or -1 if not found.
--- @field insert fun(self: List, value: unknown, position: number|nil) Inserts a `value` at the specified `position`, or at the end of the list if `position` is nil.
--- @field removeElementAt fun(self: List, position: number|nil): unknown Removes and returns the element at the specified `position`, or the last element if `position` is nil.
--- @field size fun(self: List): number Returns the number of elements in the list.
---
