--- @meta
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            

--
--- Represents a central hub for sharing and accessing objects within a specific scope,
--- either the framework itself or an individual plugin. It provides methods for exporting 
--- (registering) and importing (retrieving) objects using unique identifiers.
--- 
--- @class Context
--- 
--- @field objects? table<string, unknown>  (Optional) A table to store exported objects, indexed by their unique identifiers.
--- @field export fun(self: Context, identifier: string, object: unknown)  Registers an object in the context under a specified identifier.
--- @field import fun(self: Context, identifier: string): unknown  Retrieves a previously exported object from the context using its identifier.
--

--
--- A function that transforms a given table into a Context object, enabling it to store
--- and share objects within its scope (either the framework or a plugin).
--- 
--- @alias ContextConstructor fun(target: table): Context
--
