--- @meta
--
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- A function that registers a service within the framework. It associates a unique
--- identifier with the service, which can be represented by either a function or a table
--- containing its functionality or API.
---
--- @alias services.registerService fun(identifier: string, object: function|table)
---
