--- @meta

---
--- Defines an alias for an array of a generic type `T`. This alias simplifies the
--- notation for working with arrays of any type, improving code readability when
--- dealing with generic arrays in function signatures and type definitions.
---
--- @alias array<T> T[]
---

---
--- Represents the extended set of Lua types, including custom types introduced
--- in the framework such as `array`, `empty-table`, and `undefined`.
---
--- @alias extendedType 'undefined'
---                   | 'boolean'
---                   | 'string'
---                   | 'number'
---                   | 'array'
---                   | 'table'
---                   | 'empty-table'
---                   | 'function'
---                   | 'thread'
---                   | 'userdata'
---
