---@meta

---
--- Represents the extended set of Lua types, including custom types introduced
--- in the framework such as `array`, `empty-table`, and `undefined`.
---
--- @alias xtype.type 'undefined'
---                 | 'boolean'
---                 | 'character'
---                 | 'string'
---                 | 'number'
---                 | 'array'
---                 | 'table'
---                 | 'empty-table'
---                 | 'function'
---                 | 'thread'
---                 | 'userdata'
---
