---@meta

---
--- Represents a task that is queued for asynchronous execution. Each task contains 
--- a unique identifier, a callback function to be executed, and optional arguments 
--- that are passed to the callback.
---
--- @class task
--- 
--- @field identifier string    "A unique identifier for the task, used for tracking and execution."
--- @field callback   function  "The function to be executed when the task is processed."
--- @field arguments? unknown[] "Optional arguments to pass to the callback function when executed."
---
