--- @meta
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- An interface for a context handler that provides object storage and retrieval,
--- allowing internal objects to be exposed for use elsewhere in the system.
--- 
--- @class context
--- 
--- @field objects table<string, unknown>
--- @field import fun(identifier: string): unknown
--- @field export fun(identifier: string, object: unknown)
---
