--- @meta
--
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- This API manages the configuration of plugins, providing methods to retrieve,
--- update, and apply default settings. It allows for the retrieval of individual 
--- settings by their identifier, modification of settings, and the application 
--- of a set of default settings for the plugin.
---
--- @class config.api
--- 
--- @field getSetting fun(self: plugin, identifier: string): unknown
--- @field setSetting fun(self: plugin, identifier: string, value: unknown)
--- @field setDefaultSettings fun(self: plugin, settings: table)
---
