--- @meta
--
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- ?
---
--- @class config.api
--- 
--- @field getSetting fun(self: plugin, identifier: string): unknown
--- @field setSetting fun(self: plugin, identifier: string, value: unknown)
--- @field setDefaultSettings fun(self: plugin, settings: table)
---
