--- @meta
--
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- Manages the interaction with a plugin's settings, offering methods to retrieve,
--- update, and register default settings within the plugin's context.
---
--- @class config.handler
--- 
--- @field getSetting fun(context: plugin, identifier: string): unknown?
--- @field setSetting fun(context: plugin, identifier: string, value: unknown)
--- @field registerDefaultSettings fun(context: plugin, settings: table)
---
