--- @meta
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- Centralizes event handling logic by providing methods to trigger events, register
--- listeners for specific events (optionally associating them with a plugin context),
--- and remove listeners by their identifiers and associated plugin context.
--- 
--- @class events.handler
--- 
--- @field invokeEvent      fun(event: string, arguments?: unknown[])
--- @field registerListener fun(event: string, listener: listener, context?: plugin)
--- @field removeListener   fun(event: string, identifier: string, context?: plugin)
---
