@startuml Cogspinner
!include style.puml

component "framework" as Framework <<API>>
component "plugins" as Plugins <<manager>>

Framework ..> Plugins

component "plugin" as Plugin <<object>>

Plugins --> Plugin : <<create>>

component "channels" as Network <<controller>>
component "events" as Event <<handler>>

Plugins --> Network
Event -right-> Network

Plugin ..> Network
Plugin ..> Event

component "callbacks" as Dispatch <<handler>>

Network --> Dispatch
Event --> Dispatch

component "locales" as Locale <<manager>>

Framework ..> Locale
Plugin .right.> Locale

component "storage" as Store <<controller>>

Plugin .left.> Store
Store --> Network
Store --> Event

component "services" as Service <<manager>>

Framework .> Service

@enduml