---@meta

---
---@alias AnchorPoint 'TOPLEFT'
---                 | 'TOPRIGHT'
---                 | 'BOTTOMLEFT'
---                 | 'BOTTOMRIGHT'
---                 | 'TOP'
---                 | 'BOTTOM'
---                 | 'LEFT'
---                 | 'RIGHT'
---                 | 'CENTER'
---
