@startuml Style

skinparam {
  ' General:
  BackgroundColor #292828

  ' Component:
  ComponentBorderColor #51462A
  ComponentBackgroundColor #252424
  ComponentFontColor #CAB069
  ComponentFontName Yu Gothic UI Semibold
  ComponentFontSize 12pt

  ' ComponentStereotype:
  ComponentStereotypeFontName Consolas
  ComponentStereotypeFontSize 10pt
  ComponentStereotypeFontColor #A9B665

  ' Arrow:
  ArrowColor #655834
  ArrowHeadColor #8D7B49
  ArrowFontName Consolas
  ArrowFontSize 10pt
  ArrowFontStyle bold
  ArrowFontColor #CAB069

  ' Note:
  NoteFontName Franklin Gothic Medium
  NoteFontSize 11pt
  NoteFontColor #54492C
  NoteBorderColor #8D7B49
  NoteBackgroundColor #CAB069
}

' skinparam InterfaceBackgroundColor Orange

@enduml