@startuml Cogspinner

skinparam ComponentBackgroundColor GhostWhite
skinparam ComponentBorderColor #565656
skinparam ComponentFontStyle normal
skinparam ComponentFontSize 13pt
skinparam ComponentStereotypeFontSize 11pt
skinparam ComponentStereotypeFontStyle bold
skinparam ComponentStereotypeFontColor #515151
skinparam InterfaceBackgroundColor Orange
skinparam NoteFontStyle bold
skinparam NoteFontSize 12pt
skinparam NoteFontColor black
skinparam NoteBackgroundColor #FEFFDD
skinparam NoteBorderColor #96968D
skinparam ArrowFontSize 12pt
skinparam ArrowFontStyle bold

' interfaces:

() " " as API
() " " as pluginAPI

' framework modules:

[network manager] as channel <<module>>
[data store] as data <<module>>
[event handler] as event <<module>>
[exchange manager] as exchange <<module>>
[locale manager] as locale <<module>>
[plugin manager] as plugin <<module>>
[service manager] as service <<module>>
[task processor] as task <<core module>>
[tooltip controller] as tooltip <<module>>
[utilities] as utilities <<library>>

' notes:

note left of API: Framework API
note left of pluginAPI: Plugin API

' 

API .> plugin
API ..> locale
API .up.> tooltip
API ..> utilities
API .right.> exchange
API .up.> service

plugin --> pluginAPI : <<create>>

pluginAPI ..> channel
pluginAPI .up.> locale
pluginAPI ..> event
pluginAPI .> data

event -> task : <<use>>
channel --> task : <<use>>

@enduml