--- @meta
--
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- This specialized API interface enables plugins to interact with the command registration system,
--- allowing them to register handlers and respond to user-entered slash commands.
--- 
--- @class commands.api
---
--- @field registerCommandHandler fun(self: plugin, options: { identifier: string, command: string|string[], callback: commands.callback })
---
