--- @meta
--
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- ?
--- 
--- @class storage.api
--- 
--- @field getAccountVariable storage.api.getVariable
--- @field setAccountVariable storage.api.setVariable
--- @field getCharacterVariable storage.api.getVariable
--- @field setCharacterVariable storage.api.setVariable
---
