--- @meta
--
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- Defines the possible scopes for plugin data storage:
--- * `account` (shared across all characters on an account)
--- * `character` (specific to a single character).
---
--- @alias storage.scope 'account'|'character'
---
