--- @meta
--
--    ____                      _                       
--   / ___|___   __ _ ___ _ __ (_)_ __  _ __   ___ _ __ 
--  | |   / _ \ / _` / __| '_ \| | '_ \| '_ \ / _ \ '__|
--  | |__| (_) | (_| \__ \ |_) | | | | | | | |  __/ |   
--   \____\___/ \__, |___/ .__/|_|_| |_|_| |_|\___|_|   
--              |___/    |_|                            
--

---
--- ?
---
--- @class storage.unit
--- 
--- @field data? table
--- 
--- @field getVariable fun(self: storage.unit, path: string): unknown?
--- @field setVariable fun(self: storage.unit, path: string, value: unknown)
---

---
--- ?
---
--- @alias storage.unit.constructor fun(variable: string): storage.unit
---
